"""Build teams out of the ones humans actually brought.

Experiment 0024 found the pool every self-play measurement rests on is
generated by a *singles* format -- `gen9championsrandombattle` carries no
`gameType`, and Champions ships no random doubles generator. Tailwind, Trick
Room, Rage Powder, Follow Me and Helping Hand are on **0.0%** of those teams
and used by humans in 6-31% of real battles. So the agent has never once been
measured in a game where the opponent had speed control or redirection.

The corpus is the fix that needs no invention: every replay names all six
Pokemon each player brought, in `|poke|` lines, and 500 replays therefore carry
about a thousand real teams against the 24 generated ones we had.

**What a replay does not give is a full set.** Only a move somebody actually
clicked was ever seen, so sets are assembled from evidence pooled across the
whole corpus rather than read off a single battle:

- **moves** come from a real partial set -- the moves one player was seen using
  on that species in one battle -- topped up from what that species most
  commonly runs. Sampling a real partial set first is what keeps two Landorus
  on two different teams from being identical, which taking the global top four
  would guarantee;
- **ability and item** are the most common observed. Many abilities never
  announce themselves, so when the corpus never saw one the fallback is
  Showdown's own curated `sets.json`, which lists the ability each species
  competitively runs -- Torkoal's Drought rather than the dex's first entry,
  White Smoke. Only the abilities are taken from that file: its *movepools*
  come from the singles generator and are the very thing 0024 is about;
- **stat points and nature** are not observable at all, so they take the same
  values the generated pool uses: 11 in every stat, which is exactly Reg M-B's
  66-point budget, and a neutral nature. Inventing a spread would be inventing
  data.

Nothing here decides whether a team is legal. `TeamPool.from_texts` hands each
one to the engine, which rejects anything that is not a lawful Reg M-B team --
a real gate, not a self-assessment.
"""

import json
import random
import re
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path

from champions_ai.data.choices import extract_choices
from champions_ai.data.replay import Replay
from champions_ai.dex import to_id

# `|poke|p1|Farigiraf, L50, M|` -- the team sheet, present in every replay.
_POKE = re.compile(r"^\|poke\|(p[12])\|([^,|]+)")
# `|switch|p1a: Nickname|Farigiraf, L50, M|100/100` -- how a nickname is tied
# to a species. Without this the move log cannot be attributed at all, because
# players rename their Pokemon.
_SWITCH = re.compile(r"^\|(?:switch|drag|replace)\|([^|]+)\|([^,|]+)")
_ABILITY = re.compile(r"^\|-ability\|([^|]+)\|([^|]+)")
_ITEM = re.compile(r"^\|-(?:item|enditem)\|([^|]+)\|([^|]+)")

MOVES_PER_POKEMON = 4
TEAM_SIZE = 6
# Reg M-B allows 66 points with at most 32 in one stat. Six stats at 11 spends
# exactly the budget, and is what the generated pool uses -- so a harvested
# team differs from a generated one in species and moves, which is the thing
# under test, and in nothing else.
POINTS_PER_STAT = 11
NEUTRAL_NATURE = "Serious"


@dataclass
class SpeciesEvidence:
    """Everything the corpus ever showed about one species."""

    moves: Counter = field(default_factory=Counter)
    abilities: Counter = field(default_factory=Counter)
    items: Counter = field(default_factory=Counter)
    # One entry per (battle, player) the species appeared for: the moves that
    # player was seen using on it. Partial by construction, and real.
    observed_sets: list[tuple[str, ...]] = field(default_factory=list)

    @property
    def appearances(self) -> int:
        return len(self.observed_sets)


def _nickname_map(log: tuple[str, ...]) -> dict[tuple[str, str], str]:
    """`(side, nickname)` -> species id, from the switch lines.

    Keyed on the side as well as the name because `ObservedChoice.actor` is
    the bare nickname -- players rename their Pokemon, and two of them can
    perfectly well pick the same name.
    """
    out: dict[tuple[str, str], str] = {}
    for line in log:
        match = _SWITCH.match(line)
        if match:
            ident = match.group(1).strip()
            out[(_side_of(ident), _nickname_of(ident))] = to_id(match.group(2))
    return out


def _side_of(ident: str) -> str:
    """`p1a: Nickname` -> `p1`."""
    return ident[:2]


def _nickname_of(ident: str) -> str:
    """`p1a: Nickname` -> `Nickname`."""
    _, _, name = ident.partition(":")
    return name.strip() or ident


def brought(log: tuple[str, ...]) -> dict[str, list[str]]:
    """The six species each player brought, from the team sheet."""
    out: dict[str, list[str]] = defaultdict(list)
    for line in log:
        match = _POKE.match(line)
        if match:
            out[match.group(1)].append(to_id(match.group(2)))
    return dict(out)


def gather_evidence(replays: list[Replay]) -> dict[str, SpeciesEvidence]:
    """Pool what every species was seen doing, across the whole corpus."""
    evidence: dict[str, SpeciesEvidence] = defaultdict(SpeciesEvidence)

    for replay in replays:
        names = _nickname_map(replay.log)
        # moves this battle, per (side, species), so one appearance yields one
        # partial set rather than one entry per click
        per_side: dict[tuple[str, str], set[str]] = defaultdict(set)

        for choice in extract_choices(replay.log):
            if choice.kind != "move" or not choice.move or not choice.actor:
                continue
            side = f"p{choice.player + 1}"
            species = names.get((side, choice.actor.strip()))
            if species is None:
                continue
            per_side[(side, species)].add(to_id(choice.move))

        for line in replay.log:
            ability = _ABILITY.match(line)
            if ability:
                ident = ability.group(1).strip()
                species = names.get((_side_of(ident), _nickname_of(ident)))
                if species:
                    evidence[species].abilities[to_id(ability.group(2))] += 1
            item = _ITEM.match(line)
            if item:
                ident = item.group(1).strip()
                species = names.get((_side_of(ident), _nickname_of(ident)))
                if species:
                    evidence[species].items[to_id(item.group(2))] += 1

        for (_, species), moves in per_side.items():
            record = evidence[species]
            record.observed_sets.append(tuple(sorted(moves)))
            record.moves.update(moves)

    return dict(evidence)


# Showdown ships curated competitive sets for Champions. Only the ability
# lists are read: the movepools belong to the singles generator.
SETS_JSON = Path("node_modules/pokemon-showdown/data/random-battles/champions/sets.json")


def competitive_abilities(path: Path = SETS_JSON) -> dict[str, str]:
    """species id -> the ability it competitively runs, from Showdown's sets.

    Empty when the file is not there, which makes this a bonus rather than a
    dependency: the dex fallback still produces a legal team.
    """
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    out: dict[str, str] = {}
    for species, entry in raw.items():
        for one in entry.get("sets", ()):
            abilities = one.get("abilities") or ()
            if abilities:
                out[to_id(species)] = to_id(abilities[0])
                break
    return out


def build_set(
    species: str,
    evidence: dict[str, SpeciesEvidence],
    rng: random.Random,
    *,
    dex=None,
    fallback_abilities: dict[str, str] | None = None,
    taken_items: set[str] | None = None,
) -> str | None:
    """One Pokemon in Showdown's export format, or None if too little is known.

    Returns None rather than guessing when the corpus never saw the species use
    a move. A team with an empty moveset is not a conservative approximation of
    a real one -- it is a Pokemon that can only Struggle, which would quietly
    weaken every team carrying it.
    """
    record = evidence.get(species)
    if record is None or not record.moves:
        return None

    # A real partial set first, so two copies of the same species on different
    # teams differ the way real ones do; then the species' common moves to fill.
    moves: list[str] = []
    if record.observed_sets:
        moves.extend(rng.choice(record.observed_sets))
    for move, _ in record.moves.most_common():
        if len(moves) >= MOVES_PER_POKEMON:
            break
        if move not in moves:
            moves.append(move)
    moves = moves[:MOVES_PER_POKEMON]
    if not moves:
        return None

    # `|-ability|` announces the ability that is *active*, which after Trace,
    # Skill Swap or Mummy is somebody else's. Taking the most common observed
    # one unchecked put Pixilate and Fairy Aura on Pokemon that cannot have
    # them, and the engine rejected the whole team for it. Only abilities the
    # species actually owns are believed.
    legal: set[str] = set()
    if dex is not None:
        try:
            legal = {to_id(a) for a in dex.get_species(species).abilities}
        except (KeyError, AttributeError):
            legal = set()
    ability = next(
        (a for a, _ in record.abilities.most_common() if not legal or a in legal),
        None,
    )
    if ability is None and fallback_abilities:
        ability = fallback_abilities.get(species)
    if ability is None and legal:
        ability = sorted(legal)[0]

    # Reg M-B runs Item Clause -- one of each item per team. Every species
    # answering "Sitrus Berry" independently is how a team ends up with three
    # of them, so the choice is made against what the rest of the team already
    # holds.
    item = next(
        (
            candidate
            for candidate, _ in record.items.most_common()
            if taken_items is None or candidate not in taken_items
        ),
        None,
    )
    if item and taken_items is not None:
        taken_items.add(item)

    head = species if not item else f"{species} @ {item}"
    lines = [head]
    if ability:
        lines.append(f"Ability: {ability}")
    lines.append("Level: 50")
    lines.append(
        "EVs: "
        + " / ".join(
            f"{POINTS_PER_STAT} {stat}" for stat in ("HP", "Atk", "Def", "SpA", "SpD", "Spe")
        )
    )
    lines.append(f"{NEUTRAL_NATURE} Nature")
    lines.extend(f"- {move}" for move in moves)
    return "\n".join(lines)


def harvest_teams(
    replays: list[Replay],
    *,
    dex=None,
    seed: int = 0,
    evidence: dict[str, SpeciesEvidence] | None = None,
    fallback_abilities: dict[str, str] | None = None,
) -> list[str]:
    """Showdown export text for every team the corpus can fully assemble.

    A team is kept only when all six of its Pokemon can be built. Dropping the
    incomplete ones biases the pool toward species the corpus saw often, which
    is a bias toward *what people actually bring* -- the opposite of the
    problem 0024 found, and the reason the drop rate is worth reporting.
    """
    if evidence is None:
        evidence = gather_evidence(replays)
    if fallback_abilities is None:
        fallback_abilities = competitive_abilities()
    rng = random.Random(seed)

    texts: list[str] = []
    for replay in replays:
        for _, species in sorted(brought(replay.log).items()):
            if len(species) != TEAM_SIZE or len(set(species)) != TEAM_SIZE:
                continue  # Species Clause, or a sheet we could not read
            # One set of held items per team, shared across its six Pokemon,
            # because Item Clause is a team-level rule and each species asked
            # on its own answers "Sitrus Berry".
            taken_items: set[str] = set()
            sets = [
                build_set(
                    s,
                    evidence,
                    rng,
                    dex=dex,
                    fallback_abilities=fallback_abilities,
                    taken_items=taken_items,
                )
                for s in species
            ]
            if any(s is None for s in sets):
                continue
            texts.append("\n\n".join(s for s in sets if s is not None))
    return texts


# How frozen pools are stored: one Showdown export per team.
POOL_SEPARATOR = "\n\n===\n\n"


def harvested_pool(
    bridge,
    battle_format: str,
    replays: list[Replay],
    *,
    dex=None,
    seed: int = 0,
    limit: int | None = None,
    cache: Path | None = None,
):
    """A `TeamPool` of real teams, with the engine as the only gate.

    Every candidate goes through `validate_team`; anything the engine refuses
    is dropped and counted rather than repaired here, because a team the engine
    will not start is not a team. Roughly 96% survive.

    Pass the **train** split. The corpus also supplies the human-agreement
    benchmarks, and building the teams we measure on out of the battles we
    grade against is the leak experiment 0014 already caught once.

    `cache` freezes the pool to a file, and measurements that compare across
    runs need it. Without it the pool is rebuilt from whatever is on disk, so a
    corpus that is still being collected silently changes what every run is
    measured on: the train split moved 405 -> 923 -> 1,391 in a single session,
    and two runs of the same A/B drew different teams and disagreed by 1.4
    points because of it. Within one run both arms share a pool and the
    comparison is still sound; across runs it is not.

    The cached teams are re-validated on load rather than trusted, so a frozen
    pool cannot outlive a Showdown update that makes one of them illegal.
    """
    from champions_ai.data.team_pool import BattleTeam, TeamPool
    from champions_ai.data.team_text import parse_showdown_team

    if cache is not None and cache.exists():
        texts = [
            text
            for text in cache.read_text(encoding="utf-8").split(POOL_SEPARATOR)
            if text.strip()
        ]
    else:
        texts = harvest_teams(replays, dex=dex, seed=seed)

    teams: list[BattleTeam] = []
    kept_texts: list[str] = []
    for text in texts:
        if limit is not None and len(teams) >= limit:
            break
        try:
            packed = bridge.validate_team(battle_format, text)
        except Exception:
            continue
        teams.append(
            BattleTeam(
                team=parse_showdown_team(text),
                packed=packed,
                name=f"harvested-{len(teams)}",
            )
        )
        kept_texts.append(text)

    if cache is not None and not cache.exists():
        cache.parent.mkdir(parents=True, exist_ok=True)
        cache.write_text(POOL_SEPARATOR.join(kept_texts), encoding="utf-8")
    return TeamPool(teams)
