"""A whole battle played through domain types, not raw protocol strings.

This is the real proof that the domain model and the simulator agree: every
choice is generated by `legal_joint_actions` from an `Observation` and rendered
back with `format_joint_action`. Any disagreement shows up as the engine
rejecting a choice, which fails the test.
"""

import random

import pytest

from champions_ai.data import parse_showdown_team
from champions_ai.domain import (
    REGULATION_M_B,
    JointAction,
    PassAction,
    SwitchAction,
    TeamPreviewAction,
    legal_joint_actions,
    legal_slot_actions,
)
from champions_ai.simulator import BattleTracker, format_joint_action, format_team_preview

pytestmark = pytest.mark.integration




def _decide(tracker: BattleTracker, rng: random.Random) -> str | None:
    if tracker.waiting:
        return None

    if tracker.awaiting_team_preview:
        picks = tuple(rng.sample(range(6), REGULATION_M_B.picked_team_size))
        return format_team_preview(TeamPreviewAction(picks=picks))

    observation = tracker.observation()
    move_data = tracker.move_data
    forced = tracker.force_switch_slots

    if forced:
        # Only flagged slots act; the rest must explicitly pass.
        chosen: set[int] = set()
        slots = []
        for slot, must_switch in enumerate(forced):
            if not must_switch:
                slots.append(PassAction())
                continue
            options = [
                action
                for action in legal_slot_actions(observation, slot, move_data)
                if not isinstance(action, SwitchAction) or action.team_index not in chosen
            ]
            pick = rng.choice(options)
            if isinstance(pick, SwitchAction):
                chosen.add(pick.team_index)
            slots.append(pick)
        return format_joint_action(JointAction(slot_actions=tuple(slots)))

    return format_joint_action(rng.choice(legal_joint_actions(observation, move_data)))


def _play_through_domain(
    bridge, battle_format: str, packed: str, seed: str, rng_seed: int, team_text: str
):
    own_team = parse_showdown_team(team_text)
    trackers = {
        "p1": BattleTracker(REGULATION_M_B, player=0, own_team=own_team),
        "p2": BattleTracker(REGULATION_M_B, player=1, own_team=own_team),
    }
    rng = random.Random(rng_seed)
    events = bridge.start_battle(battle_format, packed, packed, seed=seed)

    for _ in range(400):
        pending = set()
        for event in events:
            assert event["type"] != "error", f"engine rejected a generated action: {event}"
            for tracker in trackers.values():
                tracker.handle(event)
            if event["type"] == "request":
                pending.add(event["player"])

        if trackers["p1"].finished or not pending:
            break

        events = []
        for player in sorted(pending):
            choice = _decide(trackers[player], rng)
            if choice:
                events.extend(bridge.choose(player, choice))

    return trackers


@pytest.fixture(scope="module")
def played(bridge, battle_format, mega_team_text):
    """One battle played entirely through domain types, shared by the assertions below."""
    packed = bridge.validate_team(battle_format, mega_team_text)
    return _play_through_domain(
        bridge, battle_format, packed, "sodium," + "5a" * 32, 11, mega_team_text
    )


def test_a_full_battle_plays_through_domain_types(played):
    """Every action generated by our own code is accepted by the engine."""
    p1 = played["p1"]
    assert p1.finished
    assert p1.winner in ("P1", "P2")
    assert p1.observation().turn > 0


def test_observation_never_exposes_exact_opponent_hp(played):
    observation = played["p1"].observation()
    assert observation.opponent_side.revealed
    for mon in observation.opponent_side.revealed:
        assert 0 <= mon.hp_percent <= 100


def test_opponent_moves_are_only_known_once_used(played, mega_team_text):
    observation = played["p1"].observation()
    revealed = {
        move for mon in observation.opponent_side.revealed for move in mon.revealed_moves
    }
    # Both sides run the same team, so anything revealed must belong to it --
    # and strictly fewer moves than the team actually knows.
    all_moves = {
        move.lower().replace(" ", "")
        for mon in parse_showdown_team(mega_team_text).pokemon
        for move in mon.moves
    }
    assert revealed <= all_moves
    assert len(revealed) < len(all_moves)


def test_move_data_is_learned_without_any_data_file(played):
    """Move target types come from the engine's requests, not a shipped table."""
    move_data = played["p1"].move_data
    assert len(move_data) >= 8
    assert {m.target for m in move_data.values()} & {"normal", "self", "allAdjacentFoes"}
